version: "3.8"
services:
  eureka-discovery-service:
    image: axterium/eureka-discovery-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    ports:
      - "8761:8761"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://eureka-discovery-service:8761/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - app-net

  kafka:
    image: confluentinc/cp-kafka:7.5.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT_INTERNAL:PLAINTEXT,PLAINTEXT_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: PLAINTEXT_INTERNAL://0.0.0.0:29092,PLAINTEXT_EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT_INTERNAL://kafka:29092,PLAINTEXT_EXTERNAL://localhost:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper
    networks:
      - app-net

  elasticsearch:
    image: elasticsearch:9.0.3
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    networks:
      - app-net

  api-gateway-service:
    image: axterium/api-gateway-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-discovery-service:8761/eureka/
      - IP_LOCATION_API_TOKEN=${IP_LOCATION_API_TOKEN}
    ports:
      - "8080:8080"
    depends_on:
      - eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://api-gateway-service:8080/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  auth-service:
    image: axterium/auth-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://auth-db:5432/auth_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=nTDmGYqtvLfDCptgzwG+xKGtXV/JHL4fHKJrxK9tHdI=
      - JWT_EXPIRATION=604800000
      - JWT_REFRESH_EXPIRATION=86400000
    ports:
      - "8081:8081"
    depends_on:
      - auth-db
      - eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://auth-service:8081/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  auth-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    ports:
      - "5433:5432"
    volumes:
      - auth_data:/var/lib/postgresql/data
    networks:
      - app-net

  product-service:
    image: axterium/product-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/product_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_ELASTICSEARCH_URIS=elasticsearch:9200
      - JWT_SECRET=nTDmGYqtvLfDCptgzwG+xKGtXV/JHL4fHKJrxK9tHdI=
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    ports:
      - "8082:8082"
    depends_on:
      - product-db
      - eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://product-service:8082/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  product-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: product_db
    ports:
      - "5434:5432"
    volumes:
      - product_data:/var/lib/postgresql/data
    networks:
      - app-net

  cart-service:
    image: axterium/cart-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - EUREKA_URL=http://eureka-discovery-service:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://cart-db:5432/cart_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - JWT_SECRET=nTDmGYqtvLfDCptgzwG+xKGtXV/JHL4fHKJrxK9tHdI=
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    ports:
      - "8083:8083"
    depends_on:
      - cart-db
      - eureka-discovery-service
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://cart-service:8083/actuator/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - app-net

  cart-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cart_db
    ports:
      - "5435:5432"
    volumes:
      - cart_data:/var/lib/postgresql/data
    networks:
      - app-net

  order-service:
    image: axterium/order-service:latest
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/order_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - EUREKA_URL=http://eureka-discovery-service:8761/eureka/
      - KAFKA_BOOTSTRAP_SERVERS=kafka:29092
    depends_on:
      - order-db
      - eureka-discovery-service
      - kafka
    ports:
      - "8084:8084"
    networks:
      - app-net

  order-db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: order_db
    ports:
      - "5436:5432"
    volumes:
      - order_data:/var/lib/postgresql/data
    networks:
      - app-net

volumes:
  auth_data:
  product_data:
  cart_data:
  order_data:

networks:
  app-net:
    driver: bridge