server:
  port: 8080

spring:
  application:
    name: API-GATEWAY
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: auth_service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth/**
          filters:
            - RewritePath=/auth/v3/api-docs, /v3/api-docs
        - id: product_service
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/api/products/**, /api/products
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/products/v3/api-docs, /v3/api-docs
        - id: cart-service
          uri: lb://CART-SERVICE
          predicates:
            - Path=/api/cart/**, /api/cart
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/cart/v3/api-docs, /v3/api-docs
        - id: order-service
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/api/orders/**, /api/orders
          filters:
            - JwtAuthenticationFilter
            - RewritePath=/api/orders/v3/api-docs, /v3/api-docs

springdoc:
  swagger-ui:
    urls:
      - name: Auth Service
        url: /auth/v3/api-docs
      - name: Product Service
        url: /api/products/v3/api-docs
      - name: Cart Service
        url: /api/cart/v3/api-docs
      - name: Order Service
        url: /api/orders/v3/api-docs
    path: /swagger-ui.html
    persist-authorization: true
    display-operation-id: true

jwt:
  secret: ${JWT_SECRET:"nTDmGYqtvLfDCptgzwG+xKGtXV/JHL4fHKJrxK9tHdI="}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
